"""
This file's purpose is to generate completion sentences for the model to answer.
"""

import re
from typing import Iterable

import spacy
from spacy.tokens import Doc

nlp = spacy.load("en_core_web_sm")

PRONOUNS = {
    "he", "she", "it", "they", "we", "i",
    "his", "her", "its", "their", "our", "my",
    "him", "them", "us"
}


def contains_bad_pronoun(sentence: str, doc: Doc):
    """
    Checks whether the sentence contains pronoun without the entity referenced by the pronoun.
    :param sentence: The sentence to check
    :param doc: The Doc generated by processing the sentence with nlp
    :return: whether the sentence contains pronoun without the entity referenced by the pronoun.
    """
    words = [w.text.lower() for w in doc]
    pronouns = set(words) & PRONOUNS
    if not pronouns:
        return False  # no bad pronouns

    # If pronouns exist but no entity before them → reject
    for token in doc:
        if token.text.lower() in PRONOUNS:
            # check if there's a named entity before this pronoun
            ents_before = [ent for ent in doc.ents if ent.label_ == 'PERSON' and ent.start < token.i]
            if not ents_before:
                return True  # bad pronoun usage
    return False


def is_question_ok(sentence: str, ent):
    """
    Checks whether the sentence used for question wouldn't contain the answer and isn't too short.
    :param sentence: The sentence to check
    :param ent: The expected answer to be used.
    :return: Whether this completion sentence will be viable
    """
    if sentence.count(ent.text) > 1:
        return False

    if sentence.count(' ') < 3:
        return False

    return True


def generate_completion_questions(paragraph: str, topics: Iterable[str]):
    """
    Given a paragraph and some topics, generates some completion sentences with an unambiguous answer for those topics.
    :param paragraph: The paragraph to generate the sentence from
    :param topics: A list of topics of the question, i.e. a list of short sub-string of the paragraph that the question will contain at least on of them.
    :yields: A dictionary representing the completion sentence:
        question: The completion sentence itself
        answer: The expected completion
        entity_type: The type of the answer
        prev_sentence: The sentence before the completion sentence used as the question.
        topics: A list of the topics that appear in the sentence or answer.
    """
    # Split into sentences
    sentences = re.split(r'(?<=[.!?])\s+', paragraph)

    for i, sentence in enumerate(sentences):
        topics_in_sentence = [topic for topic in topics if topic.lower() in sentence.lower()]
        if not topics_in_sentence:
            continue

        doc = nlp(sentence)

        # Reject sentences with unresolved pronouns
        if contains_bad_pronoun(sentence, doc):
            continue

        # Check for named entities at the end
        for ent in doc.ents:
            if sentence.strip().strip('.').endswith(ent.text):
                if ent.label_ in {"PERSON", "DATE", "GPE", "ORG", "CARDINAL"}:

                    if not is_question_ok(sentence, ent):
                        continue

                    question = sentence.replace(ent.text, "")

                    yield {
                        "question": question.strip(),
                        "answer": ent.text.strip(),
                        "entity_type": ent.label_,
                        "prev_sentence": sentences[i - 1] if i > 0 else '',
                        'topics': topics_in_sentence
                    }
